spring:
  datasource:
    url: jdbc:mysql://192.168.0.91:3306/white_jotter?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia%2fShanghai
    username: win
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
